### ISSUE TITLE
Creating a project

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#85]
On the page listing the Projects in a WG  (e.g.,  http://portal.lsstdesc.org/Pubs/show_swg.jsp?swgid=4), I am not seeing how to add a new Project.  I don't think  that the issue is permissions; I am listed as a Convener.  Browsing around, I am not seeing any obvious way to do it from other pages.  I must have forgotten something.  In any case, I think we need a way for conveners to be able to create Projects from pages like the one at the URL above.

**Comment by chee999** [comment]
This should be fixed now. Can you confirm?

**Comment by sethdigel** [comment]
I am afraid that it is still not working for me (i.e., I do not get the 'Create Project' button), in either Dev or Prod.  Here's part of a screen shot.  I was logged in as 'digel'.

<img width="608" alt="pubsys_proj" src="https://user-images.githubusercontent.com/6035835/42488928-0fef6872-83bd-11e8-9a28-ef14d6a4f09c.png">

**Comment by chee999** [comment]
This is working now.
